### PR TITLE
RSpec/Capybara/Jasmine Test Setup

### PR DESCRIPTION
**Pull request by esposito**
test setup

### CODE REVIEW

**Comment by CompuIves** [comment]
LGTM

**Comment by esposito** [comment]
alias guard="(bundle check || bundle) && while bundle exec guard; do echo \"Restarting Guard...\"; done"

**Comment by esposito** [comment]
if [ -f ~/.bashrc ]; then . ~/.bashrc; fi

**Comment by esposito** [comment]
git config --global push.default simple
git config --global branch.autosetuprebase always

**Comment by CompuIves** [comment]
http://hi-messaging.herokuapp.com/

**Pull request closed without merging**
